name: Cloudflare_Nginx_Tunnel
services:
  tunnel:
    container_name: cloudflare_tunnel
    image: cloudflare/cloudflared
    command: tunnel --no-autoupdate run --token $TUNNEL_TOKEN

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 8080:80
