import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import CheckpointsProvider from "@/context/checkpoints-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased m-2 lg:mx-8 lg:mt-8 sm:mx-4 sm:mt-4 font-[family-name:var(--font-geist-sans)]`}
      >
        <main>
          <CheckpointsProvider>{children}</CheckpointsProvider>
        </main>
        <Toaster />
      </body>
    </html>
  );
}
